//! License-safe golden sources for projection and visual-regression tests.

#[cfg(test)]
use strata_core::{DomainError, SourceGeneration, SourceId};
#[cfg(test)]
use strata_source::{ByteSource, RetainedByteSource};

/// Ground-truth content class represented by a projection fixture.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectionFixtureKind {
    /// Printable, line-oriented text.
    Text,
    /// Generated instruction-like bytes with repeated prologue and return patterns.
    ExecutableCode,
    /// A valid zlib stream generated from synthetic source bytes.
    Compressed,
    /// A generated planar grayscale image without a container header.
    Image,
    /// Repeated fixed-width little-endian records.
    AlignedRecords,
    /// Aligned little-endian values that point into one declared address range.
    Pointers,
    /// Exact repeated blocks separated by small record identifiers.
    RepeatedBlocks,
}

/// One deterministic, distributable projection fixture and its acceptance metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectionGoldenFixture {
    /// Stable fixture identifier.
    pub id: &'static str,
    /// Deliberately generated content class.
    pub kind: ProjectionFixtureKind,
    /// Synthetic immutable bytes.
    pub bytes: Vec<u8>,
    /// SPDX-compatible license statement for the generated bytes.
    pub license: &'static str,
    /// Whether the bytes may be committed and redistributed with the repository.
    pub distributable: bool,
    /// Observable properties that projection tests may claim as ground truth.
    pub expected_properties: &'static [&'static str],
    /// Canonical SHA-256 of [`Self::bytes`].
    pub sha256: &'static str,
}

/// Builds the complete deterministic projection fixture suite.
#[must_use]
pub fn projection_golden_fixtures() -> Vec<ProjectionGoldenFixture> {
    vec![
        fixture(
            "projection-text-v1",
            ProjectionFixtureKind::Text,
            text_bytes(),
            &[
                "printable ASCII",
                "newline periodicity",
                "7-bit high plane clear",
            ],
            "2684760d49c9fc33de6af60a785ea61954ad9f3612d7b2880a2a095f544ea554",
        ),
        fixture(
            "projection-instruction-stream-v1",
            ProjectionFixtureKind::ExecutableCode,
            instruction_bytes(),
            &["synthetic x86-like grammar", "24-byte repeated functions"],
            "ded6ca03c38ea1d8f30a0ad96c34d5d1a651e701e200e415ced7fdfef1110805",
        ),
        fixture(
            "projection-zlib-v1",
            ProjectionFixtureKind::Compressed,
            compressed_bytes(),
            &["valid zlib stream", "generated source length 1424 bytes"],
            "31214fb047b2ed6e520ad0def28dd8275b80bed03924b4eb72db003e03b9223b",
        ),
        fixture(
            "projection-planar-image-v1",
            ProjectionFixtureKind::Image,
            image_bytes(),
            &["32x16 grayscale plane", "32-byte row width"],
            "61a5b6d81f915df0bcb1b8b93e4d1cde1a2aba295ce4c30109bfe0432a9c5670",
        ),
        fixture(
            "projection-records-v1",
            ProjectionFixtureKind::AlignedRecords,
            aligned_record_bytes(),
            &["64 records", "16-byte fixed width", "little endian"],
            "bf1bd01e5feb9c9b8bfdd1cd3b61862ae54af6aa5cb558e905147b8593c36e8c",
        ),
        fixture(
            "projection-pointers-v1",
            ProjectionFixtureKind::Pointers,
            pointer_bytes(),
            &[
                "64-bit little endian",
                "8-byte aligned",
                "targets 0x1000..0x1800",
            ],
            "4719c62e58291d65415ee44ddffb72c1de305bbaf026989d357eae38c22fe954",
        ),
        fixture(
            "projection-repetition-v1",
            ProjectionFixtureKind::RepeatedBlocks,
            repeated_bytes(),
            &["16 exact motif instances", "32-byte block width"],
            "e29b50ffe8ae30a515b9af5b688eed706ba40bcbb80e54784b5cbb4e91a8fd85",
        ),
    ]
}

const fn fixture(
    id: &'static str,
    kind: ProjectionFixtureKind,
    bytes: Vec<u8>,
    expected_properties: &'static [&'static str],
    sha256: &'static str,
) -> ProjectionGoldenFixture {
    ProjectionGoldenFixture {
        id,
        kind,
        bytes,
        license: "CC0-1.0 (synthetic)",
        distributable: true,
        expected_properties,
        sha256,
    }
}

fn text_bytes() -> Vec<u8> {
    let line = b"STRATA projection golden: text, fields, offsets, evidence.\n";
    line.iter().copied().cycle().take(512).collect()
}

fn instruction_bytes() -> Vec<u8> {
    const FUNCTION: [u8; 24] = [
        0x55, 0x48, 0x89, 0xe5, 0x48, 0x83, 0xec, 0x20, 0x48, 0x8b, 0x45, 0x08, 0x48, 0x83, 0xc0,
        0x01, 0x48, 0x89, 0x45, 0xf8, 0xc9, 0xc3, 0x90, 0x90,
    ];
    FUNCTION.into_iter().cycle().take(24 * 24).collect()
}

fn compressed_bytes() -> Vec<u8> {
    vec![
        0x78, 0xda, 0x0b, 0x0e, 0x09, 0x72, 0x0c, 0x71, 0xd4, 0x75, 0xf6, 0xf7, 0x0d, 0x08, 0x72,
        0x0d, 0x0e, 0x76, 0x75, 0xd1, 0x75, 0xf7, 0xf7, 0x71, 0x71, 0xf5, 0xab, 0x61, 0x60, 0x64,
        0x62, 0x66, 0x61, 0x65, 0x63, 0xe7, 0xe0, 0xe4, 0xe2, 0xe6, 0xe1, 0xe5, 0xe3, 0x17, 0x10,
        0x14, 0x12, 0x16, 0x11, 0x15, 0x13, 0x97, 0x90, 0x94, 0x92, 0x96, 0x91, 0x95, 0x93, 0x57,
        0x50, 0x54, 0x52, 0x56, 0x51, 0x55, 0x53, 0xd7, 0xd0, 0xd4, 0xd2, 0xd6, 0xd1, 0xd5, 0xd3,
        0x37, 0x30, 0x34, 0x32, 0x36, 0x31, 0x35, 0x33, 0xb7, 0xb0, 0xb4, 0xb2, 0xb6, 0xb1, 0xb5,
        0xb3, 0x0f, 0x1e, 0x35, 0x78, 0xd4, 0xe0, 0x51, 0x83, 0x47, 0x0d, 0x1e, 0x35, 0x98, 0x14,
        0x83, 0x01, 0x19, 0x20, 0xf3, 0x31,
    ]
}

fn image_bytes() -> Vec<u8> {
    let mut bytes = Vec::with_capacity(32 * 16);
    for y in 0_u8..16 {
        for x in 0_u8..32 {
            bytes.push(x.wrapping_mul(8) ^ y.wrapping_mul(17));
        }
    }
    bytes
}

fn aligned_record_bytes() -> Vec<u8> {
    let mut bytes = Vec::with_capacity(64 * 16);
    for record in 0_u32..64 {
        bytes.extend_from_slice(&record.to_le_bytes());
        bytes.extend_from_slice(&(record.saturating_mul(64)).to_le_bytes());
        bytes.extend_from_slice(&(0x4000_u32 | record).to_le_bytes());
        bytes.extend_from_slice(&record.rotate_left(7).to_le_bytes());
    }
    bytes
}

fn pointer_bytes() -> Vec<u8> {
    let mut bytes = Vec::with_capacity(64 * 8);
    for index in 0_u64..64 {
        let target = 0x1000_u64 + ((index * 32) % 0x800);
        bytes.extend_from_slice(&target.to_le_bytes());
    }
    bytes
}

fn repeated_bytes() -> Vec<u8> {
    let mut bytes = Vec::with_capacity(16 * 32);
    for index in 0_u8..16 {
        bytes.extend_from_slice(b"STRATA-REPEAT-GOLDEN-BLOCK-");
        bytes.extend_from_slice(&[index, index ^ 0xff, 0x00, 0xff, 0x7e]);
    }
    bytes
}

#[cfg(test)]
fn fixture_digest(bytes: &[u8]) -> Result<String, DomainError> {
    let source = RetainedByteSource::new(
        SourceId(1),
        SourceGeneration(0),
        "projection-golden",
        bytes.to_vec().into(),
    )?;
    source
        .descriptor()
        .content_digest
        .ok_or_else(|| DomainError::Internal("retained fixture digest was not sealed".to_owned()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixture_metadata_and_digests_are_complete() -> Result<(), DomainError> {
        let fixtures = projection_golden_fixtures();
        assert_eq!(fixtures.len(), 7);
        for fixture in fixtures {
            assert_eq!(fixture_digest(&fixture.bytes)?, fixture.sha256);
            assert!(fixture.distributable);
            assert!(!fixture.bytes.is_empty());
            assert!(!fixture.expected_properties.is_empty());
        }
        Ok(())
    }
}
